import {
  AbIcon,
  ArrowToBottomIcon,
  ArrowToTopIcon,
  AufIcon,
  AuslaufIcon,
  AuswurfIcon,
  BearbeitenIcon,
  BecherketteIcon,
  BeipackzettelIcon,
  BenutzerAbmeldenIcon,
  BenutzerAnmeldenIcon,
  BenutzerhinzufuegenIcon,
  BenutzerIcon,
  BenutzerverwaltungIcon,
  BenutzerWechselnIcon,
  BildschirmreinigungIcon,
  BrakesBlueIcon,
  BreadcrumbPfeilIcon,
  BuendelkontrolleIcon,
  CalendarIcon,
  ChargeIcon,
  ChargeStopIcon,
  CircleIcon,
  CloseIcon,
  CornerIcon,
  DetailsIcon,
  DiagnoseIcon,
  DigitalepositionsanzeigeIcon,
  DoorIcon,
  DoubleArrowIcon,
  DrehtellerIcon,
  DruckerIcon,
  Einrichten3Icon,
  EinrichtenIcon,
  EinschubIcon,
  EinstellungenIcon,
  EinzelachsenIcon,
  EmergencyIcon,
  EtikettiererIcon,
  ExportierenIcon,
  EyeIcon,
  FailureIcon,
  FalzgeraetIcon,
  FilmIcon,
  FilterIcon,
  FolieobenIcon,
  FolieuntenIcon,
  FormateIcon,
  FormatspeichernIcon,
  FormatvergleichenIcon,
  Formatzuruecksetzen1Icon,
  FormatzuruecksetzenIcon,
  GegenhalterIcon,
  GroupIcon,
  HakenIcon,
  HeisleimdueseIcon,
  HeisleimstationIcon,
  HilfeIcon,
  HinzufuegenIcon,
  HubstationIcon,
  ImportierenIcon,
  InformationIcon,
  KalkulationIcon,
  KameraachseIcon,
  KartonabzugIcon,
  KartonaufrichterIcon,
  KartonmagazinIcon,
  Kartontransfer2Icon,
  Kartontransfer3Icon,
  KettenvorschubIcon,
  KoordinatenIcon,
  KopierenIcon,
  LadenIcon,
  LanguageIcon,
  LaschenfalterIcon,
  LeerfahrenIcon,
  LockIcon,
  LoeschenIcon,
  MaintenanceModeIcon,
  ManualModeIcon,
  MaschinenbildIcon,
  MeldungenIcon,
  MenueIcon,
  NoConnectionIcon,
  PaketaktivIcon,
  PaketinaktivIcon,
  PalettenschemaIcon,
  PasswortIcon,
  PauseIcon,
  PfeilIcon,
  PlayIcon,
  ProductionModeIcon,
  ProduktgruppierungIcon,
  ProduktiongestopptIcon,
  ProduktmasseIcon,
  ProduktuebersetzerIcon,
  ProspektketteIcon,
  ProspektspenderIcon,
  ProspektvorschubIcon,
  QuerabschubIcon,
  RfidchipIcon,
  RoboterIcon,
  ScannerIcon,
  SchließerIcon,
  SeitengurtfordererIcon,
  SeitensigelnIcon,
  SethomeIcon,
  ShrinkIcon,
  SpeichernIcon,
  Speichernundweiter2Icon,
  Speichernundweiter3Icon,
  Splicer4erIcon,
  SplicerobenaktivIcon,
  SplicerobenIcon,
  SpliceruntenaktivIcon,
  SpliceruntenIcon,
  SpracheIcon,
  StapelbrueckenschubIcon,
  StaplerIcon,
  StartenIcon,
  StatistikIcon,
  StopIcon,
  SuchenIcon,
  TaperIcon,
  TeachinIcon,
  TemperaturIcon,
  TestrunIcon,
  TrackandtraceIcon,
  TrashIcon,
  UhrzeitIcon,
  UmstellenIcon,
  UnlockIcon,
  VerteilerIcon,
  VorIcon,
  VorsetzenIcon,
  WaageIcon,
  WarningIcon,
  WendeschneckeIcon,
  ZufuerungIcon,
  Zurueck1Icon,
  ZurueckIcon,
  ZuruecksetzenIcon,
} from "./icons";

export const IconList = {
  ab: AbIcon,
  arrowToBottom: ArrowToBottomIcon,
  arrowToTop: ArrowToTopIcon,
  auf: AufIcon,
  auslauf: AuslaufIcon,
  auswurf: AuswurfIcon,
  bearbeiten: BearbeitenIcon,
  becherkette: BecherketteIcon,
  beipackzettel: BeipackzettelIcon,
  benutzer: BenutzerIcon,
  benutzerAbmelden: BenutzerAbmeldenIcon,
  benutzerAnmelden: BenutzerAnmeldenIcon,
  benutzerhinzufuegen: BenutzerhinzufuegenIcon,
  benutzerverwaltung: BenutzerverwaltungIcon,
  benutzerWechseln: BenutzerWechselnIcon,
  bildschirmreinigung: BildschirmreinigungIcon,
  brakesBlue: BrakesBlueIcon,
  breadcrumbPfeil: BreadcrumbPfeilIcon,
  buendelkontrolle: BuendelkontrolleIcon,
  calendar: CalendarIcon,
  charge: ChargeIcon,
  chargeStop: ChargeStopIcon,
  circle: CircleIcon,
  close: CloseIcon,
  corner: CornerIcon,
  details: DetailsIcon,
  diagnose: DiagnoseIcon,
  digitalepositionsanzeige: DigitalepositionsanzeigeIcon,
  door: DoorIcon,
  doubleArrow: DoubleArrowIcon,
  drehteller: DrehtellerIcon,
  drucker: DruckerIcon,
  einrichten: EinrichtenIcon,
  einrichten3: Einrichten3Icon,
  einschub: EinschubIcon,
  einstellungen: EinstellungenIcon,
  einzelachsen: EinzelachsenIcon,
  emergency: EmergencyIcon,
  etikettierer: EtikettiererIcon,
  exportieren: ExportierenIcon,
  eye: EyeIcon,
  failure: FailureIcon,
  falzgeraet: FalzgeraetIcon,
  film: FilmIcon,
  filter: FilterIcon,
  folieoben: FolieobenIcon,
  folieunten: FolieuntenIcon,
  formate: FormateIcon,
  formatspeichern: FormatspeichernIcon,
  formatvergleichen: FormatvergleichenIcon,
  formatzuruecksetzen: FormatzuruecksetzenIcon,
  formatzuruecksetzen1: Formatzuruecksetzen1Icon,
  gegenhalter: GegenhalterIcon,
  group: GroupIcon,
  haken: HakenIcon,
  heisleimduese: HeisleimdueseIcon,
  heisleimstation: HeisleimstationIcon,
  hilfe: HilfeIcon,
  hinzufuegen: HinzufuegenIcon,
  hubstation: HubstationIcon,
  importieren: ImportierenIcon,
  information: InformationIcon,
  kalkulation: KalkulationIcon,
  kameraachse: KameraachseIcon,
  kartonabzug: KartonabzugIcon,
  kartonaufrichter: KartonaufrichterIcon,
  kartonmagazin: KartonmagazinIcon,
  kartontransfer2: Kartontransfer2Icon,
  kartontransfer3: Kartontransfer3Icon,
  kettenvorschub: KettenvorschubIcon,
  koordinaten: KoordinatenIcon,
  kopieren: KopierenIcon,
  laden: LadenIcon,
  language: LanguageIcon,
  laschenfalter: LaschenfalterIcon,
  leerfahren: LeerfahrenIcon,
  lock: LockIcon,
  loeschen: LoeschenIcon,
  maintenanceMode: MaintenanceModeIcon,
  manualMode: ManualModeIcon,
  maschinenbild: MaschinenbildIcon,
  meldungen: MeldungenIcon,
  menue: MenueIcon,
  noConnection: NoConnectionIcon,
  paketaktiv: PaketaktivIcon,
  paketinaktiv: PaketinaktivIcon,
  palettenschema: PalettenschemaIcon,
  passwort: PasswortIcon,
  pause: PauseIcon,
  pfeil: PfeilIcon,
  play: PlayIcon,
  productionMode: ProductionModeIcon,
  produktgruppierung: ProduktgruppierungIcon,
  produktiongestoppt: ProduktiongestopptIcon,
  produktmasse: ProduktmasseIcon,
  produktuebersetzer: ProduktuebersetzerIcon,
  prospektkette: ProspektketteIcon,
  prospektspender: ProspektspenderIcon,
  prospektvorschub: ProspektvorschubIcon,
  querabschub: QuerabschubIcon,
  rfidchip: RfidchipIcon,
  roboter: RoboterIcon,
  scanner: ScannerIcon,
  schließer: SchließerIcon,
  seitengurtforderer: SeitengurtfordererIcon,
  seitensigeln: SeitensigelnIcon,
  sethome: SethomeIcon,
  shrink: ShrinkIcon,
  speichern: SpeichernIcon,
  speichernundweiter2: Speichernundweiter2Icon,
  speichernundweiter3: Speichernundweiter3Icon,
  splicer4er: Splicer4erIcon,
  spliceroben: SplicerobenIcon,
  splicerobenaktiv: SplicerobenaktivIcon,
  splicerunten: SpliceruntenIcon,
  spliceruntenaktiv: SpliceruntenaktivIcon,
  sprache: SpracheIcon,
  stapelbrueckenschub: StapelbrueckenschubIcon,
  stapler: StaplerIcon,
  starten: StartenIcon,
  statistik: StatistikIcon,
  stop: StopIcon,
  suchen: SuchenIcon,
  taper: TaperIcon,
  teachin: TeachinIcon,
  temperatur: TemperaturIcon,
  testrun: TestrunIcon,
  trackandtrace: TrackandtraceIcon,
  trash: TrashIcon,
  uhrzeit: UhrzeitIcon,
  umstellen: UmstellenIcon,
  unlock: UnlockIcon,
  verteiler: VerteilerIcon,
  vor: VorIcon,
  vorsetzen: VorsetzenIcon,
  waage: WaageIcon,
  warning: WarningIcon,
  wendeschnecke: WendeschneckeIcon,
  zufuerung: ZufuerungIcon,
  zurueck: ZurueckIcon,
  zurueck1: Zurueck1Icon,
  zuruecksetzen: ZuruecksetzenIcon,
};
