export type WidgetType =
  | "AnalogClock"
  | "Batch"
  | "Current"
  | "Custom"
  | "Cycles"
  | "DigitalClock"
  | "Distribution"
  | "Failures"
  | "History"
  | "MachineState"
  | "Maintenance"
  | "Material"
  | "Output"
  | "Progress"
  | "Speed"
  | "SpeedWithTarget"
  | "Stats"
